export const mockParticipants = [
	{
		id: 1,
		firstName: 'John',
		lastName: 'Doe',
		email: 'john.doe@email.com',
		phone: '1234567890',
		emergencyName: 'Jane Doe',
		emergencyPhone: '1234567891',
		medicalConditions: '',
		tshirtSize: 'L',
		bibNumber: '001',
		deviceType: 'RFID',
		deviceId: 'DEV-001',
		rfidTagId: 'RFID-001',
		category: 'Full Marathon',
		status: 'registered',
		isAssigned: true,
	},
	{
		id: 2,
		firstName: 'Jane',
		lastName: 'Smith',
		email: 'jane.smith@email.com',
		phone: '0987654321',
		emergencyName: 'John Smith',
		emergencyPhone: '0987654322',
		medicalConditions: 'Asthma',
		tshirtSize: 'M',
		bibNumber: '002',
		deviceType: 'Running Node',
		deviceId: 'DEV-002',
		rfidTagId: 'RFID-002',
		category: 'Half Marathon',
		status: 'registered',
		isAssigned: true,
	},
	{
		id: 3,
		firstName: 'Mike',
		lastName: 'Johnson',
		email: 'mike.johnson@email.com',
		phone: '5555555555',
		emergencyName: 'Sarah Johnson',
		emergencyPhone: '5555555556',
		medicalConditions: '',
		tshirtSize: 'XL',
		bibNumber: '',
		deviceType: '',
		deviceId: '',
		rfidTagId: '',
		category: '10K',
		status: 'pending-assignment',
		isAssigned: false,
	},
	{
		id: 4,
		firstName: 'Emily',
		lastName: 'Davis',
		email: 'emily.davis@email.com',
		phone: '4444444444',
		emergencyName: 'Tom Davis',
		emergencyPhone: '4444444445',
		medicalConditions: 'Allergic to latex',
		tshirtSize: 'S',
		bibNumber: '',
		deviceType: '',
		deviceId: '',
		rfidTagId: '',
		category: 'Full Marathon',
		status: 'pending-assignment',
		isAssigned: false,
	},
];
